[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/live/workspace"
  to = "/.netlify/functions/workspace"
  status = 200

[[redirects]]
  from = "/api/live/zoho/books/invoice"
  to = "/.netlify/functions/books-invoice"
  status = 200

[[redirects]]
  from = "/api/live/*"
  to = "/.netlify/functions/live/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
